### ISSUE TITLE
Delete activity

### ISSUE THREAD

**Issue by n03l** [pR0Ps/stravaweblib#1]
Would it be possible to extend your library to also delete an activity? This doesn't seem feasible with the REST API at the moment.

**Comment by pR0Ps** [comment]
For some reason it's not listed in the [old activity documentation](https://strava.github.io/api/v3/activities/), but it is [in the new docs](https://developers.strava.com/docs/reference/#api-Activities-deleteActivityById).

This functionality is actually already available as `stravaweblib.WebClient.delete_activity(id)` since it's implemented on [`stravalib.Client`](http://pythonhosted.org/stravalib/api.html?highlight=delete#stravalib.client.Client.delete_activity) which `stravaweblib.WebClient` extends.

This means that if you don't need the other extended features that `stravaweblib` provides you can just use the basic [`stravalib` ](https://github.com/hozn/stravalib) instead.

**Comment by pR0Ps** [comment]
Actually, my bad, the reason it's in one doc and not the other is because it's been [deprecated as of 2017-03-01](https://strava.github.io/api/v3/changelog/). I'll look into adding it.

**Comment by pR0Ps** [comment]
Overrode the `delete_activity` function provided by `stravalib` to look the exact same, but use an HTTP-based implementation instead of the non-working API call. Please reopen if you have any issues with it.
